server:
    port: 8082
spring:
  rabbitmq:
    host: "localhost"
    port: 5672
  datasource:
    url: "jdbc:mysql://82.73.212.90:3307/dpm_auth"
    username: "2nowabout"
    password: "SecurePassword1!"
  jpa:
    hibernate:
      ddl-auto: update

